name: Deploy Produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy na EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            cd ${{ secrets.APP_PATH }}

            echo "📥 Sincronizando código"
            git fetch origin main
            git reset --hard origin/main

            echo "📦 Instalando dependências"
            npm ci

            echo "� Gerando cliente Prisma"
            npx prisma generate

            echo "🗄️  Executando migrations"
            npx prisma migrate deploy

            echo "🏗 Build"
            npm run build

            echo "♻️ Reload PM2"
            pm2 restart nest-api
